+incdir+../../rtl/packages
../../rtl/packages/warpforge_pkg.sv
../../rtl/common/fifo.sv
../../rtl/common/skid_buffer.sv
../../rtl/common/valid_pipeline.sv
../../rtl/memory/ram_sdp.sv
../../rtl/memory/shared_memory.sv
../../rtl/scoreboard/scoreboard.sv
../../rtl/scheduler/warp_state_table.sv
../../rtl/scheduler/warp_scheduler.sv
../../rtl/tensor/tensor_core.sv
