+incdir+../../tb/uvm
+incdir+../../tb/assertions
../../tb/uvm/warpforge_if.sv
../../tb/assertions/scoreboard_sva.sv
../../tb/assertions/scheduler_sva.sv
../../tb/assertions/tensor_core_sva.sv
../../tb/sv/scoreboard_tb.sv
../../tb/sv/scheduler_tb.sv
../../tb/sv/tensor_core_tb.sv
